"""delete comment field from feedback table

Revision ID: 488474a1ee97
Revises: 72edda615182
Create Date: 2023-11-14 21:22:12.085737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488474a1ee97'
down_revision: Union[str, None] = '72edda615182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'comment')
    #op.drop_constraint('tools_master_id_fkey', 'tools', type_='foreignkey')
    #op.create_foreign_key(None, 'tools', 'masters', ['master_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tools', type_='foreignkey')
    op.create_foreign_key('tools_master_id_fkey', 'tools', 'tools', ['master_id'], ['id'])
    op.add_column('feedbacks', sa.Column('comment', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
