"""add columns to  feedback table

Revision ID: 72edda615182
Revises: 3e65ca25743e
Create Date: 2023-11-11 14:27:32.312713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72edda615182'
down_revision: Union[str, None] = '3e65ca25743e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('estimation', sa.Integer(), nullable=False))
    op.add_column('feedbacks', sa.Column('comment', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'comment')
    op.drop_column('feedbacks', 'estimation')
    # ### end Alembic commands ###
