"""add tools fix struct

Revision ID: f2c02c3f9f19
Revises: 
Create Date: 2023-11-10 15:45:23.531359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c02c3f9f19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_title'), 'areas', ['title'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('image_path', sa.String(length=140), nullable=True),
    sa.Column('salary', sa.Numeric(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_masters_address'), 'masters', ['address'], unique=False)
    op.create_index(op.f('ix_masters_first_name'), 'masters', ['first_name'], unique=False)
    op.create_index(op.f('ix_masters_last_name'), 'masters', ['last_name'], unique=False)
    op.create_index(op.f('ix_masters_phone'), 'masters', ['phone'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_title'), 'services', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_title'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_masters_phone'), table_name='masters')
    op.drop_index(op.f('ix_masters_last_name'), table_name='masters')
    op.drop_index(op.f('ix_masters_first_name'), table_name='masters')
    op.drop_index(op.f('ix_masters_address'), table_name='masters')
    op.drop_table('masters')
    op.drop_table('tools')
    op.drop_index(op.f('ix_areas_title'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
